### list holidays
GET http://localhost:3000/holidays

### create holiday
PUT http://localhost:3000/holidays/01/05-01/
Content-Type: application/json 

{
  "name": "feriado 1"
}

### delete all holidays
DELETE http://localhost:3000/holidays/0/0

### get holiday
GET http://localhost:3000/holidays/0111111111/05-01/

### delete holiday
DELETE http://localhost:3000/holidays/0100000/corpus-christi/

# k6 run -e API_BASE=http://localhost:3000 tests-open.js